version: 2

updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  target-branch: 'deps-update'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 5
  reviewers:
    - sutanlab
  assignees:
    - sutanlab
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
